[aws]
disabled = true

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[character]
symbol = "Î»"
vicmd_symbol = "Æ›"
use_symbol_for_status = false
style_success = "bold blue"
style_failure = "bold red"

[cmd_duration]
prefix = ""
style = "italic dimmed white"

[conda]
symbol = "ï„Œ "

[directory]
prefix = ""
fish_style_pwd_dir_length = 3
style = "bold italic cyan"

[docker_context]
disabled = false

[dotnet]
symbol = "ğŸ¥… "

[git_branch]
symbol = "ğŸŒ± "
style = "bold italic purple"

[git_state]
cherry_pick = "ğŸ’ PICKING"
style = "bold italic yellow"

[git_status]
conflicted = "ğŸ³"
conflicted_count.enabled = true
ahead = "ğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
untracked_count.enabled = true
stashed = "ğŸ—ƒ"
modified = "âœ"
staged = "ğŸ™"
staged_count.enabled = true
renamed = "ğŸ‘…"
renamed_count.enabled = true
deleted = "ğŸ—‘"
deleted_count.enabled = true

[memory_usage]
disabled = false
style = "bold dimmed italic white"

[nodejs]
symbol = "ğŸ¤– "
style = "bold italic green"

[hg_branch]
symbol = "ğŸŒ± "

[hostname]
style = "bold dimmed italic green"

[jobs]
disabled = true

[package]
symbol = "ğŸ "
style = "bold orange"

[python]
pyenv_prefix = ""
style = "bold italic yellow"

[time]
format = "ğŸ•™ %T "
style = "bold italic yellow"

[username]
style_root = "bold italic red"
style_user = "bold italic yellow"
